### ISSUE TITLE
sizeof...(args)>0 处并未报错，环境：-std=c++11, g++ 7.4

### ISSUE THREAD

**Issue by Rchor** [downdemo/Cpp-Templates-2ed#1]
https://github.com/downdemo/Cpp-Templates-2ed/blob/master/content/Part1%20%E5%9F%BA%E7%A1%80/04%20%E5%8F%AF%E5%8F%98%E5%8F%82%E6%95%B0%E6%A8%A1%E6%9D%BF.md#sizeof%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by downdemo** [comment]
https://gcc.godbolt.org/z/eQEAs4

调用时才会出错，因为模板在调用时才会实例化
