### ISSUE TITLE
内容勘误

### ISSUE THREAD

**Issue by mingy532** [downdemo/Cpp-Templates-2ed#3]
”成员模板（Member Template）“一节的”声明友元以允许Stack<U>访问Stack<T>的私有成员“
原文是
” to get access to private members of Stack<T2> for any type T2:“
所以是写反了吗？

**Comment by mingy532** [comment]
加一条，在[这里](https://downdemo.gitbook.io/cpp-templates-2ed/part2-shen-ru-mo-ban/11.-shen-ru-mo-ban-ji-chu-fundamentals-in-depth/you-yuan/you-yuan-lei)
```cpp
    friend T; // 对任意类型T有效，但如果T是类类型则被忽略
```
原文是This is valid for any type T but is ignored if T is not actually a class type.

**Comment by mingy532** [comment]
再加一条，在[这里](https://downdemo.gitbook.io/cpp-templates-2ed/part2-shen-ru-mo-ban/12.-mo-ban-zhong-de-ming-cheng-names-in-template/dang-qian-shi-li-hua-he-wei-zhi-te-hua)
```cpp
        JJ* j; // J是当前实例化
```
多打了一个J 
=_=

**Comment by downdemo** [comment]
对于第一处，在类模板 A<T> 中声明 A<U> 为友元的作用是 A<U> 可以访问 A<T> 的所有私有成员，当然换个参数 A<T> 也就能访问 A<U> 所有成员，不过前者才是友元的本意。另两处已修改。感谢指正，GitBook 之后不再维护，近期会下线。
